version: "3.9"

services:
  backend:
    restart: always
    image: petrosan/doodle_backend:latest
    ports:
      - "8000:8000"

  frontend:
    restart: always
    image: petrosan/doodle_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend


