version: "3.9"

services:
  backend:
    image: doodle_backend:latest
    ports:
      - "8000:8000"

  frontend:
    image: doodle_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend


